// data.js
const marvelData = [
    { era: "Ancient", title: "Eyes of Wakanda", type: "Animated Series", universe: "Earth-616", year: "1260 BC–1896 AD", startYear: -1260 },
    { era: "WWII", title: "Captain America: The First Avenger", type: "Film", universe: "Earth-616", year: "1943–1945", startYear: 1943 },
    { era: "WWII", title: "Captain America: First Vengeance", type: "Comic", universe: "Earth-616", year: "1943–1945", startYear: 1943 },
    { era: "WWII", title: "Agent Carter (One-Shot)", type: "Short", universe: "Earth-616", year: "1946", startYear: 1946 },
    { era: "WWII", title: "Agent Carter (Seasons 1-2)", type: "TV Series", universe: "Earth-616", year: "1946–1947", startYear: 1946 },
    { era: "Foundations", title: "Fantastic Four: First Steps (One-Shot)", type: "Comic", universe: "Earth-828", year: "1960", startYear: 1960 },
    { era: "Foundations", title: "X-Men: First Class", type: "Film", universe: "Earth-10005", year: "1962", startYear: 1962 },
    { era: "Foundations", title: "The Fantastic Four: First Steps", type: "Film", universe: "Earth-828", year: "1964", startYear: 1964 },
    { era: "Foundations", title: "X-Men Origins: Wolverine", type: "Film", universe: "Earth-10005", year: "1979", startYear: 1979 },
    { era: "Foundations", title: "X-Men: Apocalypse", type: "Film", universe: "Earth-TRN414", year: "1983", startYear: 1983 },
    { era: "Foundations", title: "Marvel’s Ant-Man Prelude", type: "Comic", universe: "Earth-616", year: "c. 1987", startYear: 1987 },
    { era: "1990s", title: "X-Men: Dark Phoenix", type: "Film", universe: "Earth-TRN414", year: "1992", startYear: 1992 },
    { era: "1990s", title: "Captain Marvel", type: "Film", universe: "Earth-616", year: "1995", startYear: 1995 },
    { era: "1990s", title: "X-Men ’97", type: "Animated Series", universe: "Alternate Universe", year: "1997", startYear: 1997 },
    { era: "Pre-MCU Legacy", title: "Blade", type: "Film", universe: "Earth-26320", year: "1998", startYear: 1998 },
    { era: "Pre-MCU Legacy", title: "X-Men", type: "Film", universe: "Earth-10005", year: "2000", startYear: 2000 },
    { era: "Pre-MCU Legacy", title: "Blade II", type: "Film", universe: "Earth-26320", year: "2002", startYear: 2002 },
    { era: "Pre-MCU Legacy", title: "Spider-Man", type: "Film", universe: "Earth-96283", year: "2002", startYear: 2002 },
    { era: "Pre-MCU Legacy", title: "Daredevil", type: "Film", universe: "Earth-701306", year: "2003", startYear: 2003 },
    { era: "Pre-MCU Legacy", title: "X2: X-Men United", type: "Film", universe: "Earth-10005", year: "2003", startYear: 2003 },
    { era: "Pre-MCU Legacy", title: "Hulk", type: "Film", universe: "Earth-400083", year: "2003", startYear: 2003 },
    { era: "Pre-MCU Legacy", title: "Madame Web", type: "Film", universe: "Earth-688B", year: "2003", startYear: 2003 },
    { era: "Pre-MCU Legacy", title: "The Punisher", type: "Film", universe: "Earth-58627", year: "2004", startYear: 2004 },
    { era: "Pre-MCU Legacy", title: "Spider-Man 2", type: "Film", universe: "Earth-96283", year: "2004", startYear: 2004 },
    { era: "Pre-MCU Legacy", title: "Blade: Trinity", type: "Film", universe: "Earth-26320", year: "2004", startYear: 2004 },
    { era: "Pre-MCU Legacy", title: "Elektra", type: "Film", universe: "Earth-701306", year: "2005", startYear: 2005 },
    { era: "Pre-MCU Legacy", title: "Fantastic Four", type: "Film", universe: "Earth-121698", year: "2005", startYear: 2005 },
    { era: "Pre-MCU Legacy", title: "X-Men: The Last Stand", type: "Film", universe: "Earth-10005", year: "2006", startYear: 2006 },
    { era: "Pre-MCU Legacy", title: "Blade: The Series", type: "TV Series", universe: "Earth-26320", year: "2006", startYear: 2006 },
    { era: "Pre-MCU Legacy", title: "Ghost Rider", type: "Film", universe: "Earth-121347", year: "2007", startYear: 2007 },
    { era: "Pre-MCU Legacy", title: "Spider-Man 3", type: "Film", universe: "Earth-96283", year: "2007", startYear: 2007 },
    { era: "Pre-MCU Legacy", title: "Fantastic Four: Rise of the Silver Surfer", type: "Film", universe: "Earth-121698", year: "2007", startYear: 2007 },
    { era: "MCU Phase One", title: "Iron Man", type: "Film", universe: "Earth-616", year: "2010", startYear: 2010 },
    { era: "MCU Phase One", title: "Iron Man: I Am Iron Man!", type: "Comic", universe: "Earth-616", year: "2010", startYear: 2010 },
    { era: "MCU Phase One", title: "Iron Man 2: Public Identity", type: "Comic", universe: "Earth-616", year: "2010–2011", startYear: 2010 },
    { era: "MCU Phase One", title: "Iron Man 2", type: "Film", universe: "Earth-616", year: "2011", startYear: 2011 },
    { era: "MCU Phase One", title: "Iron Man 2: Agents of S.H.I.E.L.D.", type: "Comic", universe: "Earth-616", year: "2011", startYear: 2011 },
    { era: "MCU Phase One", title: "The Incredible Hulk", type: "Film", universe: "Earth-616", year: "2011", startYear: 2011 },
    { era: "MCU Phase One", title: "A Funny Thing Happened on the Way to Thor’s Hammer", type: "Short", universe: "Earth-616", year: "2011", startYear: 2011 },
    { era: "MCU Phase One", title: "Thor", type: "Film", universe: "Earth-616", year: "2011", startYear: 2011 },
    { era: "MCU Phase One", title: "The Consultant", type: "Short", universe: "Earth-616", year: "2011", startYear: 2011 },
    { era: "MCU Phase One", title: "Fury’s Big Week", type: "Comic", universe: "Earth-616", year: "2011", startYear: 2011 },
    { era: "MCU Phase One", title: "The Avengers: Black Widow Strikes", type: "Comic", universe: "Earth-616", year: "2011–2012", startYear: 2011 },
    { era: "MCU Phase One", title: "The Avengers", type: "Film", universe: "Earth-616", year: "2012", startYear: 2012 },
    { era: "MCU Phase One", title: "Item 47", type: "Short", universe: "Earth-616", year: "2012", startYear: 2012 },
    { era: "MCU Phase One", title: "The Amazing Spider-Man", type: "Film", universe: "Earth-120703", year: "2012", startYear: 2012 },
    { era: "MCU Phase Two", title: "Iron Man 3", type: "Film", universe: "Earth-616", year: "2012", startYear: 2012 },
    { era: "MCU Phase Two", title: "Iron Man 3 Prelude", type: "Comic", universe: "Earth-616", year: "2012", startYear: 2012 },
    { era: "MCU Phase Two", title: "All Hail the King", type: "Short", universe: "Earth-616", year: "2013", startYear: 2013 },
    { era: "MCU Phase Two", title: "The Wolverine", type: "Film", universe: "Earth-10005", year: "2013", startYear: 2013 },
    { era: "MCU Phase Two", title: "Agents of S.H.I.E.L.D. (S1E1–7)", type: "TV Series", universe: "Earth-616 Divergent", year: "2013", startYear: 2013 },
    { era: "MCU Phase Two", title: "Thor: The Dark World", type: "Film", universe: "Earth-616", year: "2013", startYear: 2013 },
    { era: "MCU Phase Two", title: "Thor: The Dark World Prelude", type: "Comic", universe: "Earth-616", year: "2012–2013", startYear: 2012 },
    { era: "MCU Phase Two", title: "Agents of S.H.I.E.L.D. (S1E8–16)", type: "TV Series", universe: "Earth-616 Divergent", year: "2013–2014", startYear: 2013 },
    { era: "MCU Phase Two", title: "Winter Soldier Infinite Comic", type: "Comic", universe: "Earth-616", year: "2014", startYear: 2014 },
    { era: "MCU Phase Two", title: "Captain America: The Winter Soldier", type: "Film", universe: "Earth-616", year: "2014", startYear: 2014 },
    { era: "MCU Phase Two", title: "Agents of S.H.I.E.L.D. (S1E17–22)", type: "TV Series", universe: "Earth-616 Divergent", year: "2014", startYear: 2014 },
    { era: "MCU Phase Two", title: "The Amazing Spider-Man 2", type: "Film", universe: "Earth-120703", year: "2014", startYear: 2014 },
    { era: "MCU Phase Two", title: "Guardians Dangerous Prey", type: "Comic", universe: "Earth-616", year: "2014", startYear: 2014 },
    { era: "MCU Phase Two", title: "Guardians of the Galaxy Prelude", type: "Comic", universe: "Earth-616", year: "2014", startYear: 2014 },
    { era: "MCU Phase Two", title: "Guardians of the Galaxy", type: "Film", universe: "Earth-616", year: "2014", startYear: 2014 },
    { era: "MCU Phase Two", title: "I Am Groot S1E1", type: "Animated Short", universe: "Earth-616", year: "2014", startYear: 2014 },
    { era: "MCU Phase Two", title: "Guardians of the Galaxy Vol. 2", type: "Film", universe: "Earth-616", year: "2014", startYear: 2014 },
    { era: "MCU Phase Two", title: "I Am Groot (rest of series)", type: "Animated Short", universe: "Earth-616", year: "2014", startYear: 2014 },
    { era: "MCU Phase Two", title: "Daredevil (S1)", type: "TV Series", universe: "Earth-616", year: "2014", startYear: 2014 },
    { era: "MCU Phase Two", title: "Jessica Jones (S1)", type: "TV Series", universe: "Earth-616", year: "2015", startYear: 2015 },
    { era: "MCU Phase Two", title: "Jessica Jones", type: "Comic", universe: "Earth-616", year: "2015", startYear: 2015 },
    { era: "MCU Phase Two", title: "Agents of S.H.I.E.L.D. (S2E1–19)", type: "TV Series", universe: "Earth-616 Divergent", year: "2014–2015", startYear: 2014 },
    { era: "MCU Phase Two", title: "Ultron Prelude – This Scepter’d Isle", type: "Comic", universe: "Earth-616", year: "2015", startYear: 2015 },
    { era: "MCU Phase Two", title: "Avengers: Age of Ultron", type: "Film", universe: "Earth-616", year: "2015", startYear: 2015 },
    { era: "MCU Phase Two", title: "Agents of S.H.I.E.L.D. (S2E20–22)", type: "TV Series", universe: "Earth-616 Divergent", year: "2015", startYear: 2015 },
    { era: "MCU Phase Two", title: "WHIH Newsfront (Ant-Man)", type: "Digital", universe: "Earth-616", year: "2015", startYear: 2015 },
    { era: "MCU Phase Two", title: "Ant-Man: Scott Lang Small Time", type: "Comic", universe: "Earth-616", year: "2015", startYear: 2015 },
    { era: "MCU Phase Two", title: "Ant-Man", type: "Film", universe: "Earth-616", year: "2015", startYear: 2015 },
    { era: "MCU Phase Two", title: "Daredevil (S2)", type: "TV Series", universe: "Earth-616", year: "2015", startYear: 2015 },
    { era: "MCU Phase Two", title: "Luke Cage (S1)", type: "TV Series", universe: "Earth-616", year: "2015", startYear: 2015 },
    { era: "MCU Phase Two", title: "Ghost Rider: Spirit of Vengeance", type: "Film", universe: "Earth-121347", year: "2015", startYear: 2015 },
    { era: "MCU Phase Three", title: "Agents of S.H.I.E.L.D. (S3E1–19)", type: "TV Series", universe: "Earth-616 Divergent", year: "2015–2016", startYear: 2015 },
    { era: "MCU Phase Three", title: "Iron Fist (S1)", type: "TV Series", universe: "Earth-616", year: "2016", startYear: 2016 },
    { era: "MCU Phase Three", title: "The Defenders", type: "TV Series", universe: "Earth-616", year: "2016", startYear: 2016 },
    { era: "MCU Phase Three", title: "WHIH Newsfront (Civil War)", type: "Digital", universe: "Earth-616", year: "2016", startYear: 2016 },
    { era: "MCU Phase Three", title: "Civil War Prelude – Crossroads", type: "Comic", universe: "Earth-616", year: "2016", startYear: 2016 },
    { era: "MCU Phase Three", title: "Captain America: Civil War", type: "Film", universe: "Earth-616", year: "2016", startYear: 2016 },
    { era: "MCU Phase Three", title: "Deadpool", type: "Film", universe: "Earth-TRN414", year: "2016", startYear: 2016 },
    { era: "MCU Phase Three", title: "Agents of S.H.I.E.L.D. (S3E20–22)", type: "TV Series", universe: "Earth-616 Divergent", year: "2016", startYear: 2016 },
    { era: "MCU Phase Three", title: "Black Widow", type: "Film", universe: "Earth-616", year: "2016", startYear: 2016 },
    { era: "MCU Phase Three", title: "Black Panther", type: "Film", universe: "Earth-616", year: "2016", startYear: 2016 },
    { era: "MCU Phase Three", title: "Black Panther Prelude", type: "Comic", universe: "Earth-616", year: "2008–2016", startYear: 2008 },
    { era: "MCU Phase Three", title: "Spider-Man: Homecoming", type: "Film", universe: "Earth-616", year: "Fall 2016", startYear: 2016 },
    { era: "MCU Phase Three", title: "The Punisher (S1)", type: "TV Series", universe: "Earth-616", year: "2016", startYear: 2016 },
    { era: "MCU Phase Three", title: "Slingshot", type: "Digital", universe: "Earth-616", year: "2016", startYear: 2016 },
    { era: "MCU Phase Three", title: "Agents of S.H.I.E.L.D. (S4)", type: "TV Series", universe: "Earth-616 Divergent", year: "2016–2017", startYear: 2016 },
    { era: "MCU Phase Three", title: "Doctor Strange Prelude", type: "Comic", universe: "Earth-616", year: "2016", startYear: 2016 },
    { era: "MCU Phase Three", title: "Doctor Strange", type: "Film", universe: "Earth-616", year: "2016–2017", startYear: 2016 },
    { era: "MCU Phase Three", title: "The New Mutants", type: "Film", universe: "Earth-TRN414", year: "2017–2019", startYear: 2017 },
    { era: "MCU Phase Three", title: "Jessica Jones (S2)", type: "TV Series", universe: "Earth-616", year: "2017", startYear: 2017 },
    { era: "MCU Phase Three", title: "Luke Cage (S2)", type: "TV Series", universe: "Earth-616", year: "2017", startYear: 2017 },
    { era: "MCU Phase Three", title: "Iron Fist (S2)", type: "TV Series", universe: "Earth-616", year: "2017", startYear: 2017 },
    { era: "MCU Phase Three", title: "Daredevil (S3)", type: "TV Series", universe: "Earth-616", year: "2017", startYear: 2017 },
    { era: "MCU Phase Three", title: "The Punisher (S2)", type: "TV Series", universe: "Earth-616", year: "2017", startYear: 2017 },
    { era: "MCU Phase Three", title: "Jessica Jones (S3)", type: "TV Series", universe: "Earth-616", year: "2017", startYear: 2017 },
    { era: "MCU Phase Three", title: "Agents of S.H.I.E.L.D. (S5E1–19)", type: "TV Series", universe: "Earth-616 Divergent", year: "2017–2018", startYear: 2017 },
    { era: "MCU Phase Three", title: "Thor: Ragnarok", type: "Film", universe: "Earth-616", year: "2017", startYear: 2017 },
    { era: "MCU Phase Three", title: "Deadpool 2", type: "Film", universe: "Earth-TRN414", year: "2018", startYear: 2018 },
    { era: "MCU Phase Three", title: "Venom", type: "Film", universe: "Earth-688B", year: "2018", startYear: 2018 },
    { era: "MCU Phase Three", title: "Ant-Man and the Wasp", type: "Film", universe: "Earth-616", year: "Spring 2018", startYear: 2018 },
    { era: "MCU Phase Three", title: "Captain Marvel Prelude", type: "Comic", universe: "Earth-616", year: "2018", startYear: 2018 },
    { era: "MCU Phase Three", title: "Infinity War Prelude", type: "Comic", universe: "Earth-616", year: "2016–2018", startYear: 2016 },
    { era: "MCU Phase Three", title: "Avengers: Infinity War", type: "Film", universe: "Earth-616", year: "Spring 2018", startYear: 2018 },
    { era: "MCU Phase Three", title: "Agents of S.H.I.E.L.D. (S5E20–22)", type: "TV Series", universe: "Earth-616 Divergent", year: "2018", startYear: 2018 },
    { era: "MCU Phase Three", title: "Agents of S.H.I.E.L.D. (S6–7)", type: "TV Series", universe: "Earth-616 Divergent", year: "2019–2020", startYear: 2019 },
    { era: "Multiverse Saga", title: "Avengers: Endgame (Prologue)", type: "Film", universe: "Earth-616", year: "2018", startYear: 2018 },
    { era: "Multiverse Saga", title: "Venom: Let There Be Carnage", type: "Film", universe: "Earth-688B", year: "2021", startYear: 2021 },
    { era: "Multiverse Saga", title: "Morbius", type: "Film", universe: "Earth-688B", year: "2022", startYear: 2022 },
    { era: "Multiverse Saga", title: "X-Men: Days of Future Past", type: "Film", universe: "Earth-10005", year: "1973, 2023", startYear: 1973 },
    { era: "Multiverse Saga", title: "Avengers: Endgame", type: "Film", universe: "Earth-616", year: "2023", startYear: 2023 },
    { era: "Multiverse Saga", title: "Loki (S1–S2)", type: "TV Series", universe: "TVA", year: "Outside Time", startYear: 2023 },
    { era: "Multiverse Saga", title: "What If...?", type: "Animated Series", universe: "Multiverse", year: "Multiverse", startYear: 2023 },
    { era: "Multiverse Saga", title: "WandaVision", type: "TV Series", universe: "Earth-616", year: "2023", startYear: 2023 },
    { era: "Multiverse Saga", title: "Shang-Chi and the Legend of the Ten Rings", type: "Film", universe: "Earth-616", year: "Spring 2024", startYear: 2024 },
    { era: "Multiverse Saga", title: "The Falcon and the Winter Soldier", type: "TV Series", universe: "Earth-616", year: "Spring 2024", startYear: 2024 },
    { era: "Multiverse Saga", title: "Spider-Man: Far From Home", type: "Film", universe: "Earth-616", year: "Summer 2024", startYear: 2024 },
    { era: "Multiverse Saga", title: "The Daily Bugle (S1–S2)", type: "Digital", universe: "Earth-616", year: "2024", startYear: 2024 },
    { era: "Multiverse Saga", title: "Venom: Let There Be Carnage (Post-Credits)", type: "Film", universe: "Earth-616/688B", year: "2024", startYear: 2024 },
    { era: "Multiverse Saga", title: "Eternals", type: "Film", universe: "Earth-616", year: "Fall 2024", startYear: 2024 },
    { era: "Multiverse Saga", title: "Spider-Man: No Way Home", type: "Film", universe: "Earth-616", year: "Fall/Winter 2024", startYear: 2024 },
    { era: "Multiverse Saga", title: "The Daily Bugle (S3)", type: "Digital", universe: "Earth-616", year: "2024", startYear: 2024 },
    { era: "Multiverse Saga", title: "Doctor Strange in the Multiverse of Madness", type: "Film", universe: "Earth-616", year: "Fall 2024", startYear: 2024 },
    { era: "Multiverse Saga", title: "Hawkeye", type: "TV Series", universe: "Earth-616", year: "Dec 2024", startYear: 2024 },
    { era: "Multiverse Saga", title: "Venom: The Last Dance", type: "Film", universe: "Earth-688B", year: "2024", startYear: 2024 },
    { era: "Multiverse Saga", title: "Kraven the Hunter", type: "Film", universe: "Earth-688B", year: "2024", startYear: 2024 },
    { era: "Multiverse Saga", title: "Moon Knight", type: "TV Series", universe: "Earth-616", year: "Spring 2025", startYear: 2025 },
    { era: "Multiverse Saga", title: "Black Panther: Wakanda Forever", type: "Film", universe: "Earth-616", year: "Spring 2025", startYear: 2025 },
    { era: "Multiverse Saga", title: "She-Hulk: Attorney at Law", type: "TV Series", universe: "Earth-616", year: "2025", startYear: 2025 },
    { era: "Multiverse Saga", title: "Echo", type: "TV Series", universe: "Earth-616", year: "May 2025", startYear: 2025 },
    { era: "Multiverse Saga", title: "Ms. Marvel", type: "TV Series", universe: "Earth-616", year: "Fall 2025", startYear: 2025 },
    { era: "Multiverse Saga", title: "Thor: Love and Thunder", type: "Film", universe: "Earth-616", year: "Fall 2025", startYear: 2025 },
    { era: "Multiverse Saga", title: "Werewolf by Night", type: "Special", universe: "Earth-616", year: "Halloween 2025", startYear: 2025 },
    { era: "Multiverse Saga", title: "The Guardians of the Galaxy Holiday Special", type: "Special", universe: "Earth-616", year: "Dec 2025", startYear: 2025 },
    { era: "Multiverse Saga", title: "Ironheart", type: "TV Series", universe: "Earth-616", year: "Late 2025", startYear: 2025 },
    { era: "Multiverse Saga", title: "Ant-Man and the Wasp: Quantumania", type: "Film", universe: "Earth-616", year: "Early 2026", startYear: 2026 },
    { era: "Multiverse Saga", title: "Guardians of the Galaxy Vol. 3", type: "Film", universe: "Earth-616", year: "2026", startYear: 2026 },
    { era: "Multiverse Saga", title: "Secret Invasion", type: "TV Series", universe: "Earth-616", year: "2026", startYear: 2026 },
    { era: "Multiverse Saga", title: "The Marvels", type: "Film", universe: "Earth-616", year: "2026", startYear: 2026 },
    { era: "Multiverse Saga", title: "Agatha All Along", type: "TV Series", universe: "Earth-616", year: "2026", startYear: 2026 },
    { era: "Multiverse Saga", title: "Deadpool & Wolverine", type: "Film", universe: "Multiverse", year: "2026", startYear: 2026 },
    { era: "Multiverse Saga", title: "Daredevil: Born Again", type: "TV Series", universe: "Earth-616", year: "2026–2027", startYear: 2026 },
    { era: "Multiverse Saga", title: "Captain America: Brave New World", type: "Film", universe: "Earth-616", year: "2027", startYear: 2027 },
    { era: "Multiverse Saga", title: "Thunderbolts*", type: "Film", universe: "Earth-616", year: "2027", startYear: 2027 },
    { era: "Multiverse Saga", title: "Avengers: Doomsday", type: "Film", universe: "Earth-616", year: "2028", startYear: 2028 },
    { era: "Multiverse Saga", title: "Avengers: Secret Wars", type: "Film", universe: "Earth-616", year: "2028–2029", startYear: 2028 },
    { era: "Multiverse Saga", title: "Logan", type: "Film", universe: "Earth-17315", year: "2029", startYear: 2029 },
];
